// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddArea(arg1) {
  return window['go']['main']['App']['AddArea'](arg1);
}

export function AddList(arg1, arg2) {
  return window['go']['main']['App']['AddList'](arg1, arg2);
}

export function AddTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2, arg3);
}

export function DeleteList(arg1) {
  return window['go']['main']['App']['DeleteList'](arg1);
}

export function GetAreas() {
  return window['go']['main']['App']['GetAreas']();
}

export function GetListBySlug(arg1) {
  return window['go']['main']['App']['GetListBySlug'](arg1);
}

export function GetLists() {
  return window['go']['main']['App']['GetLists']();
}

export function GetListsByArea(arg1) {
  return window['go']['main']['App']['GetListsByArea'](arg1);
}

export function GetTodoById(arg1) {
  return window['go']['main']['App']['GetTodoById'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function GetTodosByList(arg1) {
  return window['go']['main']['App']['GetTodosByList'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}
