// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddArea(arg1:string):Promise<void>;

export function AddList(arg1:string,arg2:string):Promise<void>;

export function AddTodo(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string):Promise<void>;

export function DeleteList(arg1:number):Promise<void>;

export function GetAreas():Promise<Array<models.Area>>;

export function GetListBySlug(arg1:string):Promise<models.List>;

export function GetLists():Promise<Array<models.List>>;

export function GetListsByArea(arg1:number):Promise<Array<models.List>>;

export function GetTodayTodos():Promise<Array<models.Todo>>;

export function GetTodoById(arg1:number):Promise<Array<models.Todo>>;

export function GetTodos():Promise<Array<models.Todo>>;

export function GetTodosByList(arg1:number):Promise<Array<models.Todo>>;

export function ToggleTodo(arg1:number):Promise<void>;

export function UpdateListArea(arg1:number,arg2:number):Promise<void>;

export function UpdateTodo(arg1:number,arg2:string,arg3:string,arg4:number,arg5:boolean,arg6:string):Promise<void>;

export function UpdateTodoList(arg1:number,arg2:number):Promise<void>;
