// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddArea(arg1:string):Promise<void>;

export function AddList(arg1:string,arg2:string):Promise<void>;

export function AddTodo(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetAreas():Promise<Array<models.Area>>;

export function GetInboxTasks():Promise<Array<models.Todo>>;

export function GetListBySlug(arg1:string):Promise<models.List>;

export function GetLists():Promise<Array<models.List>>;

export function GetListsByArea(arg1:number):Promise<Array<models.List>>;

export function GetTodoById(arg1:number):Promise<Array<models.Todo>>;

export function GetTodos():Promise<Array<models.Todo>>;

export function GetTodosByList(arg1:number):Promise<Array<models.Todo>>;

export function ToggleTodo(arg1:number):Promise<void>;
