// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddList(arg1, arg2) {
  return window['go']['main']['App']['AddList'](arg1, arg2);
}

export function AddTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2, arg3);
}

export function GetInboxTasks() {
  return window['go']['main']['App']['GetInboxTasks']();
}

export function GetListBySlug(arg1) {
  return window['go']['main']['App']['GetListBySlug'](arg1);
}

export function GetLists() {
  return window['go']['main']['App']['GetLists']();
}

export function GetTodoById(arg1) {
  return window['go']['main']['App']['GetTodoById'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}
