// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTodo(arg1:string,arg2:string):Promise<void>;

export function GetTodos():Promise<Array<models.Todo>>;

export function Greet(arg1:string):Promise<string>;
