// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddArea(arg1) {
  return window['go']['main']['App']['AddArea'](arg1);
}

export function AddList(arg1, arg2) {
  return window['go']['main']['App']['AddList'](arg1, arg2);
}

export function AddTodo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2, arg3, arg4, arg5);
}

export function CalculateRemainingTime(arg1) {
  return window['go']['main']['App']['CalculateRemainingTime'](arg1);
}

export function DeleteDeadline(arg1) {
  return window['go']['main']['App']['DeleteDeadline'](arg1);
}

export function DeleteList(arg1) {
  return window['go']['main']['App']['DeleteList'](arg1);
}

export function GetAreas() {
  return window['go']['main']['App']['GetAreas']();
}

export function GetListBySlug(arg1) {
  return window['go']['main']['App']['GetListBySlug'](arg1);
}

export function GetListCount(arg1) {
  return window['go']['main']['App']['GetListCount'](arg1);
}

export function GetLists() {
  return window['go']['main']['App']['GetLists']();
}

export function GetListsByArea(arg1) {
  return window['go']['main']['App']['GetListsByArea'](arg1);
}

export function GetListsWithoutArea() {
  return window['go']['main']['App']['GetListsWithoutArea']();
}

export function GetTodayCount() {
  return window['go']['main']['App']['GetTodayCount']();
}

export function GetTodayTodos() {
  return window['go']['main']['App']['GetTodayTodos']();
}

export function GetTodoById(arg1) {
  return window['go']['main']['App']['GetTodoById'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function GetTodosByList(arg1) {
  return window['go']['main']['App']['GetTodosByList'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}

export function UpdateListArea(arg1, arg2) {
  return window['go']['main']['App']['UpdateListArea'](arg1, arg2);
}

export function UpdateTodo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTodoList(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodoList'](arg1, arg2);
}
